namespace ClubService.Domain.Event;

public enum EventType
{
    TENNIS_CLUB_REGISTERED,
    MEMBER_REGISTERED,
    MEMBER_LIMIT_EXCEEDED,
    MEMBER_DELETED,
    ADMIN_ACCOUNT_CREATED,
    ADMIN_ACCOUNT_DELETED,
    TENNIS_CLUB_SUBSCRIPTION_TIER_CHANGED,
    MEMBER_LOCKED,
    MEMBER_UNLOCKED,
    MEMBER_UPDATED,
    TENNIS_CLUB_LOCKED,
    TENNIS_CLUB_UNLOCKED,
    SUBSCRIPTION_TIER_CREATED
}