namespace ClubService.Domain.Event;

public enum EventType
{
    TENNIS_CLUB_REGISTERED,
    MEMBER_REGISTERED,
    MEMBER_DELETED,
    ADMIN_REGISTERED,
    ADMIN_DELETED,
    FULL_NAME_CHANGED,
    TENNIS_CLUB_SUBSCRIPTION_TIER_CHANGED,
    MEMBER_LOCKED,
    MEMBER_UNLOCKED,
    MEMBER_UPDATED,
    TENNIS_CLUB_LOCKED,
    TENNIS_CLUB_UNLOCKED,
    SUBSCRIPTION_TIER_CREATED,
    TENNIS_CLUB_NAME_CHANGED,
    TENNIS_CLUB_DELETED
}