version: '3.9'

services:
  redis:
    image: redis:7.0-alpine
    container_name: "club-service-redis"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tennis-club-network
  
  debezium-postgres:
    ports:
      - "5432:5432"
  
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: "club-service-mailhog"
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"