version: '3.9'

services:
  club-service:
    image: club-service
    container_name: "club-service"
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    depends_on:
      - debezium-postgres
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - tennis-club-network
  
  debezium-postgres:
    image: debezium/postgres:16-alpine
    container_name: "club-service-postgres"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: club-service-event-store
    networks:
      - tennis-club-network
  
  debezium:
    image: debezium/server
    container_name: "club-service-debezium"
    restart: always
    ports:
      - "54326:8080"
    depends_on:
      - club-service
      - debezium-postgres
    volumes:
      - ./debezium-conf:/debezium/conf
    networks:
      - tennis-club-network

networks:
  tennis-club-network:
    name: tennis-club-network
    driver: bridge