services:
  club-service:
    image: club-service
    container_name: "club-service"
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    depends_on:
      - debezium-postgres
      - redis
    ports:
      - "5000:8080"
      - "5001:8081"
  
  redis:
    image: redis:7.0-alpine
    container_name: "club-service-redis"
    restart: always
    ports:
      - "6379:6379"
  
  debezium-postgres:
    image: debezium/postgres:16-alpine
    container_name: "club-service-postgres"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: club-service-event-store
    ports:
      - "5432:5432"
  
  debezium:
    image: debezium/server
    container_name: "club-service-debezium"
    restart: always
    ports:
      - "54326:8080"
    depends_on:
      - debezium-postgres
      - redis
    volumes:
      - ./debezium-conf:/debezium/conf