services:
  clubservice:
    image: clubservice
    container_name: "club-service"
    build:
      context: .
      dockerfile: ./Dockerfile
  redis:
    image: redis
    container_name: "club-service-redis"
    ports:
      - "6379:6379"
  debezium-postgres:
    image: debezium/postgres:16-alpine
    container_name: "club-service-postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: club-service
    ports:
      - "5432:5432"