apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-service-debezium-deployment
  labels:
    app: club-service-debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: club-service-debezium
  template:
    metadata:
      labels:
        app: club-service-debezium
    spec:
      containers:
        - name: club-service-debezium
          image: debezium/server
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: club-service-debezium-config
              mountPath: /debezium/conf
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: club-service-postgres-config
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: club-service-postgres-config
                  key: postgres-port
            - name: POSTGRES_EVENT_STORE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: club-service-postgres-config
                  key: postgres-event-store-db-name
                  
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: club-service-postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: club-service-postgres-secret
                  key: postgres-password
          
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-port
      restartPolicy: Always
      volumes:
        - name: club-service-debezium-config
          configMap:
            name: club-service-debezium-config    
---
apiVersion: v1
kind: Service
metadata:
  name: club-service-debezium-service
spec:
  selector:
    app: club-service-debezium
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080   