apiVersion: v1
kind: ConfigMap
metadata:
  name: club-service-debezium-config
data:
  application.properties: |
    # source config (postgres)
    debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
    debezium.source.offset.storage.file.filename=data/offsets.dat
    debezium.source.offset.flush.interval.ms=0
    debezium.source.database.hostname=${POSTGRES_HOST}
    debezium.source.database.port=${POSTGRES_PORT}
    debezium.source.database.user=${POSTGRES_USER}
    debezium.source.database.password=${POSTGRES_PASSWORD}
    debezium.source.database.dbname=${POSTGRES_EVENT_STORE_DB_NAME}
    debezium.source.plugin.name=pgoutput
    debezium.source.topic.prefix=club_service_events
    debezium.source.schema.include.list=public
    
    # sink config (redis)
    debezium.sink.type=redis
    debezium.sink.redis.address=${REDIS_HOST}:${REDIS_PORT}
    #debezium.sink.redis.user=WE HAVE NO USER CONFIGURED SO WE COMMENT THIS
    #debezium.sink.redis.password=WE HAVE NO PASSWORD CONFIGURED SO WE COMMENT THIS
    
    # disable logging in json, so we are actually able to read something
    quarkus.log.console.json=false