// <auto-generated />
using System;
using ClubService.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubService.Infrastructure.Migrations.LoginStore
{
    [DbContext(typeof(LoginStoreDbContext))]
    [Migration("20240709210524_InitialLoginStore")]
    partial class InitialLoginStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubService.Domain.Model.Entity.UserPassword", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashedPassword");

                    b.HasKey("UserId")
                        .HasName("pK_UserPassword");

                    b.ToTable("UserPassword", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1588ec27-c932-4dee-a341-d18c8108a711"),
                            HashedPassword = "AQAAAAIAAYagAAAAEDUKJ7ReV2uEyekYGEB91VvXGmWH+HwRO9wfUHnqgb5QHs0NJTac+/OUJbiInt64zg=="
                        },
                        new
                        {
                            UserId = new Guid("1dd88382-f781-4bf8-94e3-05e99d1434fe"),
                            HashedPassword = "AQAAAAIAAYagAAAAEINUWsPuMng880Mae+aQWYsWtBOozyrGRXjlwTzpZhgI5IAbm0g+JoI0kDdPkrKBfA=="
                        },
                        new
                        {
                            UserId = new Guid("4a2eb3dc-7f1e-4dac-851a-667594ca31ff"),
                            HashedPassword = "AQAAAAIAAYagAAAAEBKu/YIpt3bJSChT1BW8kziF2PcNfbYrn/ar4ApIvo9CCoTypAWnJaWV4SsNTfTaYg=="
                        },
                        new
                        {
                            UserId = new Guid("5d2f1aec-1cc6-440a-b04f-ba8b3085a35a"),
                            HashedPassword = "AQAAAAIAAYagAAAAEGT6tP27VLg6Fj8DqqMkzoXM1u5ZPMFlx9QJY4c/aBb3jGng1ySWdmC7l3w6hknQCw=="
                        },
                        new
                        {
                            UserId = new Guid("60831440-06d2-4017-9a7b-016e9cd0b2dc"),
                            HashedPassword = "AQAAAAIAAYagAAAAEOHyHLp7O2x6x+SSomU58BNU/B3SwbkVe1iW8mI3kJCbx/3ltTcee3VNfC6O8xpOrQ=="
                        },
                        new
                        {
                            UserId = new Guid("51ae7aca-2bb8-421a-a923-2ba2eb94bb3a"),
                            HashedPassword = "AQAAAAIAAYagAAAAEINyI26mDpfR+H5XGY+1zwGWGqT5+1jkHC9rxFDUNC3xcTlFyf9en7A64cfrLmhQ7Q=="
                        },
                        new
                        {
                            UserId = new Guid("e8a2cd4c-69ad-4cf2-bca6-a60d88be6649"),
                            HashedPassword = "AQAAAAIAAYagAAAAEAWIvUbmCZPblT7HngkrZ1f4zfBtO8WGDd4SScg1ZZPE7SlytGjjxbLI1hPm0DePjw=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
