// <auto-generated />
using System;
using ClubService.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubService.Infrastructure.Migrations.LoginStore
{
    [DbContext(typeof(LoginStoreDbContext))]
    partial class LoginStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubService.Domain.Model.Entity.UserPassword", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashedPassword");

                    b.HasKey("UserId")
                        .HasName("pK_UserPassword");

                    b.ToTable("UserPassword", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1588ec27-c932-4dee-a341-d18c8108a711"),
                            HashedPassword = "AQAAAAIAAYagAAAAEDUKJ7ReV2uEyekYGEB91VvXGmWH+HwRO9wfUHnqgb5QHs0NJTac+/OUJbiInt64zg=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
